name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn install

      - name: Run test
        run: yarn hardhat test

  test-l2:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn install

      - name: Checkout ethereum-optimism/optimism
        uses: actions/checkout@v2
        with:
          repository: ethereum-optimism/optimism
          path: optimism

      - name: Build
        run: docker-compose build && echo Build complete
        working-directory: optimism/ops
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1

      - name: Start L2
        run: |
          docker-compose up -d
          ./scripts/wait-for-sequencer.sh
        working-directory: optimism/ops

      - name: Run test
        run: yarn hardhat test
